services:
  tunebot:
    container_name: tunebot
    build: .
    restart: unless-stopped
    environment:
      DISCORD_BOT_TOKEN: ""
      DISCORD_PREFIX: "!"
      SPOTIFY_CLIENT_ID: ""
      SPOTIFY_CLIENT_SECRET: ""